services:
  gateway:
    image: ${DOCKERHUB_USERNAME}/bbd-gateway:latest
    container_name: bbd-gateway
    ports:
      - "8080:8080"

  user:
    image: ${DOCKERHUB_USERNAME}/bbd-user:latest
    container_name: bbd-user
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: public
      DB_ENDPOINT: ${USER_DB_ENDPOINT}
      DB_NAME: ${USER_DB_USERNAME}
      DB_PASSWORD: ${USER_DB_PASSWORD}
    restart: always

  item:
    image: ${DOCKERHUB_USERNAME}/bbd-item:latest
    container_name: bbd-item
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: public
      DB_ENDPOINT: ${ITEM_DB_ENDPOINT}
      DB_NAME: ${ITEM_DB_USERNAME}
      DB_PASSWORD: ${ITEM_DB_PASSWORD}
    restart: always

  inventory:
    image: ${DOCKERHUB_USERNAME}/bbd-inventory:latest
    container_name: bbd-inventory
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: public
      DB_ENDPOINT: ${INVENTORY_DB_ENDPOINT}
      DB_NAME: ${INVENTORY_DB_USERNAME}
      DB_PASSWORD: ${INVENTORY_DB_PASSWORD}
    restart: always

  procurement:
    image: ${DOCKERHUB_USERNAME}/bbd-procurement:latest
    container_name: bbd-procurement
    ports:
      - "8084:8080"
    environment:
      SPRING_PROFILES_ACTIVE: public
      DB_ENDPOINT: ${PROCUREMENT_DB_ENDPOINT}
      DB_NAME: ${PROCUREMENT_DB_USERNAME}
      DB_PASSWORD: ${PROCUREMENT_DB_PASSWORD}
    restart: always

  sales:
    image: ${DOCKERHUB_USERNAME}/bbd-sales:latest
    container_name: bbd-sales
    ports:
      - "8085:8080"
    environment:
      SPRING_PROFILES_ACTIVE: public
      DB_ENDPOINT: ${SALES_DB_ENDPOINT}
      DB_NAME: ${SALES_DB_USERNAME}
      DB_PASSWORD: ${SALES_DB_PASSWORD}
    restart: always